#!MANAGED-CONFIG $subs_link interval=43200 strict=true

[General]
loglevel = notify
encrypted-dns-server = https://dns.cloudflare.com/dns-query, https://dns.google/dns-query
encrypted-dns-follow-outbound-mode = true
tun-excluded-routes = 0.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.168.0.0/16, 192.88.99.0/24, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32
skip-proxy = localhost, *.local, injections.adguard.org, local.adguard.org, captive.apple.com, guzzoni.apple.com, 0.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.168.0.0/16, 192.88.99.0/24, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 240.0.0.0/4, 255.255.255.255/32
wifi-assist = true
allow-wifi-access = true
wifi-access-http-port = 16152
wifi-access-socks5-port = 16153
http-listen = 0.0.0.0:16152
socks5-listen = 0.0.0.0:16153
replica = false
tls-provider = openssl
network-framework = false
exclude-simple-hostnames = true
ipv6 = true
test-timeout = 4
proxy-test-url = http://www.gstatic.com/generate_204
geoip-maxmind-url = https://unpkg.zhimg.com/rulestatic@1.0.1/Country.mmdb

[Replica]
hide-apple-request = true
hide-crashlytics-request = true
use-keyword-filter = false
hide-udp = false

[Panel]
SubscribeInfo = $subscribe_info, style=info

[Proxy]
$proxies

[Proxy Group]
{{PROXY_GROUPS}}

[Host]
dns.cloudflare.com = 1.1.1.1
dns.google = 8.8.8.8
dns.alidns.com = 223.5.5.5
{{DNS_HOSTS}}

[Rule]
DOMAIN,dns.cloudflare.com,♻️ 延迟优选
DOMAIN,dns.google,♻️ 延迟优选
DOMAIN,dns.alidns.com,DIRECT
DOMAIN,$subs_domain,DIRECT
