#!MANAGED-CONFIG $subs_link interval=43200 strict=true

[General]
loglevel = notify
ipv6 = false
dns-server = 223.6.6.6, 119.29.29.29
proxy-test-url = http://www.gstatic.com/generate_204

[Panel]
SubscribeInfo = $subscribe_info, style=info

[Proxy]
$proxies

[Proxy Group]
Proxy = select, auto, fallback, $proxy_group
auto = url-test, $proxy_group, url=http://www.gstatic.com/generate_204, interval=300
fallback = fallback, $proxy_group, url=http://www.gstatic.com/generate_204, interval=300

[Rule]
DOMAIN,$subs_domain,DIRECT
